import json
import os
import smtplib
import html
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import datetime
import logging
from string import Template
from dotenv import load_dotenv

load_dotenv()

# Setup logging
os.makedirs("logs", exist_ok=True)
logging.basicConfig(
    filename=f"logs/build_{datetime.datetime.now(datetime.timezone.utc).date().isoformat()}.log",
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)
console = logging.StreamHandler()
console.setLevel(logging.INFO)
logging.getLogger("").addHandler(console)

CURATED_ITEMS_FILE = "data/curated_items.json"

HTML_TEMPLATE = Template("""
<!DOCTYPE html>
<html>
<head>
<style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }
    h1 { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }
    h2 { color: #2980b9; margin-top: 30px; }
    .item { margin-bottom: 25px; padding: 15px; background: #f8f9fa; border-radius: 5px; border-left: 4px solid #3498db; }
    .item-title { font-size: 1.2em; font-weight: bold; margin-bottom: 10px; }
    .item-title a { color: #2980b9; text-decoration: none; }
    .item-title a:hover { text-decoration: underline; }
    .summary { margin-bottom: 10px; }
    .why-it-matters { font-style: italic; color: #16a085; font-weight: 500; }
    .footer { margin-top: 40px; font-size: 0.9em; color: #7f8c8d; text-align: center; border-top: 1px solid #eee; padding-top: 20px; }
</style>
</head>
<body>
    <h1>AI Builders Newsletter - $date</h1>
    <p>Here are the top curated AI tools, research, and agents for today.</p>
    
    $content
    
    <div class="footer">
        Generated by AI Tools Newsletter Pipeline
    </div>
</body>
</html>
""")

CATEGORY_TEMPLATE = Template("""
    <h2>$category</h2>
    $items
""")

ITEM_TEMPLATE = Template("""
    <div class="item">
        <div class="item-title"><a href="$url">$title</a></div>
        <div class="summary">$summary</div>
        <div class="why-it-matters">Why it matters for builders: $why_it_matters</div>
    </div>
""")

def send_email(subject, html_content, recipient):
    user = os.getenv("GMAIL_USER")
    password = os.getenv("GMAIL_APP_PASSWORD")
    
    if not user or not password:
        logging.error("Gmail credentials missing. Cannot send email.")
        return False
        
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = user
    msg["To"] = recipient
    
    msg.attach(MIMEText(html_content, "html"))
    
    try:
        logging.info(f"Connecting to Gmail SMTP to send draft to {recipient}...")
        server = smtplib.SMTP("smtp.gmail.com", 587, timeout=15)
        server.starttls()
        server.login(user, password)
        server.sendmail(user, recipient, msg.as_string())
        server.quit()
        logging.info("Email sent successfully.")
        return True
    except Exception as e:
        logging.error(f"Failed to send email: {e}")
        return False

def main():
    if not os.path.exists(CURATED_ITEMS_FILE):
        logging.error(f"{CURATED_ITEMS_FILE} not found. Cannot build draft.")
        return
        
    with open(CURATED_ITEMS_FILE, "r", encoding="utf-8") as f:
        data = json.load(f)
        
    items = data.get("curated_items", [])
    if not items:
        logging.warning("No items in curated data to build draft.")
        return
        
    # Group by category
    grouped = {"Tools": [], "Research": [], "Agents": []}
    for item in items:
        cat = item.get("category", "Tools")
        if cat not in grouped:
            grouped[cat] = []
        grouped[cat].append(item)
        
    # Render HTML
    content_html = ""
    for cat in ["Tools", "Research", "Agents"]:
        cat_items = grouped.get(cat, [])
        if not cat_items:
            continue
            
        items_html = ""
        for it in cat_items:
            items_html += ITEM_TEMPLATE.substitute(
                url=html.escape(it.get("url", "#"), quote=True),
                title=html.escape(it.get("title", "Untitled")),
                summary=html.escape(it.get("summary", "")),
                why_it_matters=html.escape(it.get("why_it_matters", ""))
            )
            
        content_html += CATEGORY_TEMPLATE.substitute(
            category=cat,
            items=items_html
        )
        
    today_str = datetime.datetime.now(datetime.timezone.utc).date().isoformat()
    final_html = HTML_TEMPLATE.substitute(
        date=today_str,
        content=content_html
    )
    
    # Save to file
    os.makedirs("drafts", exist_ok=True)
    draft_path = f"drafts/{today_str}.html"
    with open(draft_path, "w", encoding="utf-8") as f:
        f.write(final_html)
    logging.info(f"Draft saved to {draft_path}")
    
    # Also save the JSON for approve_and_send reference
    draft_json_path = f"drafts/{today_str}.json"
    with open(draft_json_path, "w", encoding="utf-8") as f:
        json.dump(items, f, indent=2)
        
    # Send draft via email
    if os.getenv("DRY_RUN", "false").lower() != "true":
        send_email(f"[REVIEW] Newsletter draft {today_str}", final_html, os.getenv("GMAIL_USER"))
    else:
        logging.info("DRY_RUN is enabled. Not sending draft email.")

if __name__ == "__main__":
    main()
